const { getFullModeInputs } = require("../utils/fullModeInput");
const { getLightModeInputs } = require("../utils/lightModeInput");
const { createProject } = require("../utils/setups/projectSetup");
const {
  setupCleanArchitecture,
} = require("../utils/configs/setupCleanArchitecture");
const {
  setupLightArchitecture,
} = require("../utils/configs/setupLightArchitecture");
const { setupAuth } = require("../utils/setups/setupAuth");
const { setupSwagger } = require("../utils/setups/setupSwagger");
const { setupDatabase } = require("../utils/setups/setupDatabase");
const { configureDocker } = require("../utils/configs/configureDocker");
const { setupBootstrapLogger } = require("../utils/setups/setupLogger");
const { logSuccess } = require("../utils/loggers/logSuccess");
const { logInfo } = require("../utils/loggers/logInfo");
const { logError } = require("../utils/loggers/logError");
const { generateEnvFile, writeEnvFile } = require("../utils/envGenerator");
const readline = require("readline-sync");
const { info, warning } = require("../utils/colors");
const { logWarning } = require("../utils/loggers/logWarning");

async function newCommand(projectName, flags = {}) {
  if (!projectName) {
    console.log("\n Welcome to NestCraftX CLI \n");

    let currentProjectName = "";
    let isValid = false;

    currentProjectName = readline.question(
      `${info("[?]")} Project name [my-app] : `
    ); // Boucle de validation

    while (!isValid) {
      // La valeur est valide si elle passe la RegEx ET qu'elle n'est pas vide
      const passesRegex = /^[A-Za-z][A-Za-z0-9_-]*$/.test(currentProjectName);

      if (currentProjectName && passesRegex) {
        isValid = true;
      } else {
        logWarning(
          "Invalid or missing name. Use letters, numbers, _ or - (must start with a letter)."
        );
        currentProjectName = readline.question(
          `${info("[?]")} Project name : `,
          { placeholder: "my-app" }
        );
      }
    }

    const inputs = await getFullModeInputs(currentProjectName, flags);
    return executeProjectSetup(inputs);
  }

  const mode = determineMode(flags);
  const inputs =
    mode === "light"
      ? await buildLightModeInputs(projectName, flags)
      : await buildFullModeInputs(projectName, flags);

  return executeProjectSetup(inputs);
}

function determineMode(flags) {
  if (flags.light) return "light";
  if (flags.full) return "full";
  if (flags.mode) return flags.mode;
  return "full";
}

async function buildLightModeInputs(projectName, flags) {
  const hasAllRequiredFlags = hasAllLightModeFlags(flags);

  if (hasAllRequiredFlags) {
    console.log(" LIGHT Mode - Quick configuration (via flags)\n");
    return buildLightModeFromFlags(projectName, flags);
  }

  return getLightModeInputs(projectName, flags);
}

async function buildFullModeInputs(projectName, flags) {
  // 1. Tente de construire les inputs avec les flags si l'ORM est fourni (mode non-interactif)
  if (hasAllFullModeFlags(flags)) {
    console.log(" FULL Mode - Quick configuration (via flags)\n");
    return buildFullModeFromFlags(projectName, flags);
  }

  // 2. Sinon, utiliser la fonction interactive
  const inputs = await getFullModeInputs(projectName, flags);
  inputs.projectName = projectName;
  inputs.mode = "full";

  return inputs;
}

function hasAllLightModeFlags(flags) {
  // Logique interne, pas de traduction nécessaire
  if (!flags.interactive || flags.interactive === false) {
    return false;
  }
  return true;
}

function buildLightModeFromFlags(projectName, flags) {
  const orm = flags.orm || "prisma";
  const validOrms = ["prisma", "typeorm", "mongoose"];

  if (!validOrms.includes(orm)) {
    logError(`Unrecognized ORM: ${orm}. Using Prisma by default.`);
  }

  const inputs = {
    projectName,
    mode: "light",
    useYarn: false,
    useDocker: flags.docker !== false,
    useAuth: !!flags.auth,
    useSwagger: !!flags.swagger,
    swaggerInputs: flags.swagger
      ? {
          title: `${projectName} API`,
          description: "API generated by NestCraftX",
          version: "1.0.0",
          endpoint: "api/docs",
        }
      : undefined,
    packageManager: "npm",
    entitiesData: {
      entities: [],
      relations: [],
    },
    selectedDB: orm === "mongoose" ? "mongodb" : "postgresql",
    dbConfig:
      orm === "mongoose"
        ? {
            orm: "mongoose",
            MONGO_URI: "mongodb://localhost:27017",
            MONGO_DB: projectName,
          }
        : {
            orm: validOrms.includes(orm) ? orm : "prisma",
            POSTGRES_USER: "postgres",
            POSTGRES_PASSWORD: "postgres",
            POSTGRES_DB: projectName,
            POSTGRES_HOST: "localhost",
            POSTGRES_PORT: "5432",
          },
  };

  if (flags.auth) {
    // 🇫🇷 Auth active : ajout automatique de l'entite User
    logInfo("Auth active: User entity automatically added");
    inputs.entitiesData.entities.push({
      name: "user",
      fields: [
        { name: "email", type: "string" },
        { name: "password", type: "string" },
        { name: "isActive", type: "boolean" },
      ],
    });
  }

  return inputs;
}

function hasAllFullModeFlags(flags) {
  // Logique interne, pas de traduction nécessaire
  if (!flags.interactive || flags.interactive === false) {
    return false;
  }
  return true;
}

function buildFullModeFromFlags(projectName, flags) {
  // Logique interne, pas de traduction nécessaire
  const orm = flags.orm || "prisma";
  const validOrms = ["prisma", "typeorm", "mongoose"];
  const finalOrm = validOrms.includes(orm) ? orm : "prisma";

  const packageManager = flags.yarn ? "yarn" : "npm";

  const defaultDBConfig =
    finalOrm === "mongoose"
      ? {
          orm: finalOrm,
          MONGO_URI: flags.mongoUri || "mongodb://localhost:27017",
          MONGO_DB: flags.dbName || projectName,
        }
      : {
          orm: finalOrm,
          POSTGRES_USER: flags.dbUser || "postgres",
          POSTGRES_PASSWORD: flags.dbPassword || "postgres",
          POSTGRES_DB: flags.dbName || projectName,
          POSTGRES_HOST: flags.dbHost || "localhost",
          POSTGRES_PORT: flags.dbPort || "5432",
        };

  const useAuth = flags.auth !== false;
  const useSwagger = flags.swagger !== false;
  const useDocker = flags.docker !== false;

  const inputs = {
    projectName,
    mode: "full",
    useYarn: flags.yarn === true,
    packageManager: packageManager,
    useDocker: useDocker,
    useAuth: useAuth,
    useSwagger: useSwagger,
    swaggerInputs: useSwagger
      ? {
          title: flags.swaggerTitle || `${projectName} API`,
          description: flags.swaggerDesc || "API generated by NestCraftX",
          version: flags.swaggerVersion || "1.0.0",
          endpoint: flags.swaggerEndpoint || "api/docs",
        }
      : undefined,
    entitiesData: {
      entities: [],
      relations: [],
    },
    selectedDB: finalOrm === "mongoose" ? "mongodb" : "postgresql",
    dbConfig: defaultDBConfig,
  };

  if (useAuth) {
    inputs.entitiesData.entities.push({
      name: "user",
      fields: [
        { name: "email", type: "string" },
        { name: "password", type: "string" },
        { name: "isActive", type: "boolean" },
      ],
    });
  }

  return inputs;
}

async function executeProjectSetup(inputs) {
  try {
    logInfo("Starting project generation...");

    await createProject(inputs);

    if (inputs.mode === "light") {
      await setupLightArchitecture(inputs);
    } else {
      await setupCleanArchitecture(inputs);
    }

    if (inputs.useAuth) await setupAuth(inputs);

    if (inputs.useSwagger) {
      await setupSwagger(inputs.swaggerInputs);
    } else {
      setupBootstrapLogger();
    }

    if (inputs.useDocker) await configureDocker(inputs);

    await setupDatabase(inputs);

    const envContent = await generateEnvFile(inputs);
    writeEnvFile(envContent);

    printSuccessSummary(inputs);
  } catch (error) {
    // Erreur lors de la creation du projet: ${error.message}
    logError(`Error during project creation: ${error.message}`);
    throw error;
  }
}

function printSuccessSummary(inputs) {
  console.log("\n" + "=".repeat(60));
  logSuccess(`Project ${inputs.projectName} created successfully!`);
  console.log("=".repeat(60));

  console.log("\nConfiguration Summary:");
  console.log(`  Project: ${inputs.projectName}`);
  console.log(`  Mode: ${inputs.mode || "full"}`.toUpperCase());
  console.log(`  Database: ${inputs.selectedDB}`);
  console.log(`  ORM: ${inputs.dbConfig.orm}`);
  console.log(`  Auth: ${inputs.useAuth ? "Yes" : "No"}`);
  console.log(`  Swagger: ${inputs.useSwagger ? "Yes" : "No"}`);
  console.log(`  Docker: ${inputs.useDocker ? "Yes" : "No"}`);
  console.log(`  Entities: ${inputs.entitiesData.entities.length}`);

  console.log("\n🚀 Next Steps:");
  console.log(`  1. cd ${inputs.projectName}`);

  // --- SPECIFIC ORM/DB INSTRUCTIONS ---
  if (inputs.dbConfig.orm === "prisma" || inputs.dbConfig.orm === "typeorm") {
    // Instructions for PostgreSQL (Prisma and TypeORM)
    console.log("\n  2. Create an empty PostgreSQL database.");
    console.log("   (Ex: `createdb " + inputs.dbConfig.POSTGRES_DB + "`)");
    console.log("  3. Update the .env file with your connection details.");

    if (inputs.dbConfig.orm === "prisma") {
      console.log("\n  4. **Migrations & Seed (Prisma):**");
      console.log(`    ${inputs.packageManager} prisma migrate reset`);
      console.log(`     ${inputs.packageManager} prisma migrate dev`);
    } else {
      // TypeORM
      console.log("\n  4. **Migrations (TypeORM):**");
      console.log(`   - ${inputs.packageManager} run typeorm:migration:run`);
    }
    console.log("\n  5. Run the project:");
    console.log(`   - ${inputs.packageManager} run start:dev`);
  } else if (inputs.dbConfig.orm === "mongoose") {
    // Instructions for MongoDB (Mongoose)
    console.log("\n  2. Ensure your MongoDB server is running.");
    console.log("  3. Update the .env file (MONGO_URI variable).");
    console.log("   (The database will be created automatically)");

    console.log("\n  4. Run the project:");
    console.log(`   - ${inputs.packageManager} run start:dev`);
  }

  // --- ENDPOINTS / SWAGGER ---
  if (inputs.useSwagger) {
    console.log(
      `  6. Open Swagger UI : http://localhost:3000/${inputs.swaggerInputs.endpoint}`
    );
  }

  console.log("\nUseful commands:");
  console.log("  - nestcraftx test   Check environment");
  console.log("  - nestcraftx info   CLI information");
  console.log("  - nestcraftx --help  Complete help\n");
}

module.exports = newCommand;
